"""Tests for POST /v1/photos."""

from __future__ import annotations

import io
import json


def _jpeg_bytes() -> bytes:
    """Minimal valid JPEG (1×1 white pixel)."""
    import struct
    # Smallest valid JPEG: SOI + APP0 + SOF + DHT + SOS + EOI
    # Use a real tiny JPEG generated by PIL.
    try:
        from PIL import Image
        buf = io.BytesIO()
        Image.new("RGB", (1, 1), (255, 255, 255)).save(buf, format="JPEG")
        return buf.getvalue()
    except ImportError:
        return b"\xff\xd8\xff\xd9"  # minimal SOI+EOI


_META = json.dumps({
    "schema_version": "photo-upload-v1",
    "lr_catalog_uuid": "test-lr-uuid-001",
    "exif_snapshot": {"iso": 100},
    "lr_develop_settings": {"exposure": 0.5},
})


def test_upload_photo_creates_record(client, mock_storage):
    resp = client.post(
        "/v1/photos",
        files={"file": ("test.jpg", _jpeg_bytes(), "image/jpeg")},
        data={"metadata": _META},
    )
    assert resp.status_code == 200
    body = resp.json()
    assert "photo_id" in body
    assert body["s3_key"].startswith("photos/")
    assert body["already_existed"] is False
    mock_storage.put_object.assert_called_once()


def test_upload_photo_idempotent(client):
    """Second upload with same lr_catalog_uuid returns the existing record."""
    kwargs = dict(
        files={"file": ("test.jpg", _jpeg_bytes(), "image/jpeg")},
        data={"metadata": _META},
    )
    r1 = client.post("/v1/photos", **kwargs)
    r2 = client.post("/v1/photos", **kwargs)
    assert r1.status_code == 200
    assert r2.status_code == 200
    assert r1.json()["photo_id"] == r2.json()["photo_id"]
    assert r2.json()["already_existed"] is True


def test_upload_photo_invalid_metadata(client):
    resp = client.post(
        "/v1/photos",
        files={"file": ("test.jpg", _jpeg_bytes(), "image/jpeg")},
        data={"metadata": "not-json"},
    )
    assert resp.status_code == 422
